apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-custom
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes-custom
